export const fakeTravel = [
  {
    from: "Rabat",
    startDate: "08:00",
    endDate: "11:00",
    to: "Casablanca",
    duration: "03h00min",
    price: "120",
    transfer: false,
  },
  {
    from: "Casablanca",
    startDate: "14:30",
    endDate: "17:30",
    to: "Fes",
    duration: "03h00min",
    price: "200",
    transfer: true,
  },
  {
    from: "Fes",
    startDate: "06:15",
    endDate: "09:45",
    to: "Marrakech",
    duration: "03h30min",
    price: "250",
    transfer: true,
  },
  {
    from: "Marrakech",
    startDate: "10:00",
    endDate: "13:30",
    to: "Rabat",
    duration: "03h30min",
    price: "230",
    transfer: false,
  },
  {
    from: "Rabat",
    startDate: "15:00",
    endDate: "18:15",
    to: "Fes",
    duration: "03h15min",
    price: "180",
    transfer: false,
  },
  {
    from: "Fes",
    startDate: "11:45",
    endDate: "15:30",
    to: "Casablanca",
    duration: "03h45min",
    price: "220",
    transfer: true,
  },
  {
    from: "Casablanca",
    startDate: "09:00",
    endDate: "12:30",
    to: "Marrakech",
    duration: "03h30min",
    price: "210",
    transfer: false,
  },
  {
    from: "Marrakech",
    startDate: "13:15",
    endDate: "16:45",
    to: "Fes",
    duration: "03h30min",
    price: "250",
    transfer: true,
  },
  {
    from: "Fes",
    startDate: "07:30",
    endDate: "10:30",
    to: "Rabat",
    duration: "03h00min",
    price: "150",
    transfer: false,
  },
  {
    from: "Rabat",
    startDate: "18:00",
    endDate: "21:00",
    to: "Marrakech",
    duration: "03h00min",
    price: "240",
    transfer: true,
  },
  {
    from: "Rabat",
    startDate: "09:30",
    endDate: "12:00",
    to: "Marrakech",
    duration: "02h30min",
    price: "200",
    transfer: true,
  },
  {
    from: "Casablanca",
    startDate: "08:00",
    endDate: "11:00",
    to: "Fes",
    duration: "03h00min",
    price: "170",
    transfer: false,
  },
  {
    from: "Fes",
    startDate: "10:15",
    endDate: "13:45",
    to: "Rabat",
    duration: "03h30min",
    price: "150",
    transfer: false,
  },
  {
    from: "Marrakech",
    startDate: "14:00",
    endDate: "16:30",
    to: "Casablanca",
    duration: "02h30min",
    price: "180",
    transfer: true,
  },
  {
    from: "Rabat",
    startDate: "07:45",
    endDate: "10:15",
    to: "Fes",
    duration: "02h30min",
    price: "160",
    transfer: false,
  },
  {
    from: "Casablanca",
    startDate: "13:00",
    endDate: "15:30",
    to: "Marrakech",
    duration: "02h30min",
    price: "190",
    transfer: true,
  },
  {
    from: "Fes",
    startDate: "15:45",
    endDate: "19:00",
    to: "Marrakech",
    duration: "03h15min",
    price: "220",
    transfer: false,
  },
  {
    from: "Marrakech",
    startDate: "11:30",
    endDate: "14:00",
    to: "Rabat",
    duration: "02h30min",
    price: "210",
    transfer: true,
  },
  {
    from: "Rabat",
    startDate: "12:00",
    endDate: "15:00",
    to: "Casablanca",
    duration: "03h00min",
    price: "175",
    transfer: false,
  },
  {
    from: "Casablanca",
    startDate: "17:30",
    endDate: "20:30",
    to: "Fes",
    duration: "03h00min",
    price: "200",
    transfer: true,
  },
  {
    from: "Rabat",
    startDate: "10:15",
    endDate: "12:45",
    to: "Casablanca",
    duration: "02h30min",
    price: "160",
    transfer: false,
  },
  {
    from: "Casablanca",
    startDate: "08:30",
    endDate: "11:30",
    to: "Fes",
    duration: "03h00min",
    price: "190",
    transfer: true,
  },
  {
    from: "Fes",
    startDate: "12:00",
    endDate: "15:30",
    to: "Marrakech",
    duration: "03h30min",
    price: "240",
    transfer: false,
  },
  {
    from: "Marrakech",
    startDate: "09:00",
    endDate: "11:30",
    to: "Rabat",
    duration: "02h30min",
    price: "180",
    transfer: true,
  },
  {
    from: "Rabat",
    startDate: "14:45",
    endDate: "17:15",
    to: "Fes",
    duration: "02h30min",
    price: "175",
    transfer: false,
  },
  {
    from: "Casablanca",
    startDate: "11:00",
    endDate: "14:00",
    to: "Marrakech",
    duration: "03h00min",
    price: "200",
    transfer: true,
  },
  {
    from: "Fes",
    startDate: "15:30",
    endDate: "19:00",
    to: "Rabat",
    duration: "03h30min",
    price: "230",
    transfer: false,
  },
  {
    from: "Marrakech",
    startDate: "06:30",
    endDate: "09:00",
    to: "Casablanca",
    duration: "02h30min",
    price: "160",
    transfer: true,
  },
  {
    from: "Rabat",
    startDate: "13:30",
    endDate: "16:00",
    to: "Marrakech",
    duration: "02h30min",
    price: "190",
    transfer: false,
  },
  {
    from: "Casablanca",
    startDate: "19:00",
    endDate: "21:30",
    to: "Fes",
    duration: "02h30min",
    price: "210",
    transfer: true,
  },
];
